# Suppress secret scanning false positives in test files.
# Test vectors (e.g. RFC 4226/6238 TOTP/HOTP) are public constants,
# not real credentials.
paths-ignore:
  - "**/*Test.kt"
  - "**/Test*.kt"
  - "**/test_*.py"
  - "**/tests/**"
